CPMDeclarePackage(
  CLI11
  VERSION 2.3.2
  GITHUB_REPOSITORY CLIUtils/CLI11
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)

CPMDeclarePackage(
  Catch2
  VERSION 3.3.2
  GITHUB_REPOSITORY catchorg/Catch2
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)

CPMDeclarePackage(
  magic_enum
  GIT_TAG 8f6c9905fdf901c27093f01b16b8a756073b1ea6
  GITHUB_REPOSITORY Neargye/magic_enum
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)

CPMDeclarePackage(
  nanobench
  VERSION 4.3.11
  GITHUB_REPOSITORY martinus/nanobench
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)

CPMDeclarePackage(
  spdlog
  VERSION 1.11.0
  GITHUB_REPOSITORY gabime/spdlog
  SYSTEM YES
  EXCLUDE_FROM_ALL YES
)
